/************************************************************
 * ConsultaCEP_MVC - Firebird 3.0+
 * Execute depois de criar o banco:
 *
 * CREATE DATABASE 'C:\...\ConsultaCEP_MVC\Database\CONSULTACEP_MVC.FDB'
 *   PAGE_SIZE 16384
 *   DEFAULT CHARACTER SET UTF8;
 ************************************************************/

CREATE DOMAIN D_ID AS BIGINT NOT NULL;
CREATE DOMAIN D_CEP AS CHAR(8) CHARACTER SET UTF8
  CHECK (VALUE SIMILAR TO '[0-9]{8}');
CREATE DOMAIN D_RESULTADO AS VARCHAR(20) CHARACTER SET UTF8
  CHECK (VALUE IN ('SUCESSO', 'NAO_ENCONTRADO', 'ERRO_API', 'CEP_INVALIDO'));
CREATE DOMAIN D_DESCRICAO AS VARCHAR(200) CHARACTER SET UTF8;
CREATE DOMAIN D_NOME_CURTO AS VARCHAR(100) CHARACTER SET UTF8;
CREATE DOMAIN D_UF AS CHAR(2) CHARACTER SET UTF8;
CREATE DOMAIN D_GATEWAY AS VARCHAR(50) CHARACTER SET UTF8;
CREATE DOMAIN D_TIMESTAMP AS TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE SEQUENCE SEQ_CONSULTA_CEP;
CREATE SEQUENCE SEQ_GATEWAY_CONFIG;

CREATE TABLE CONSULTA_CEP (
  ID D_ID PRIMARY KEY,
  CEP D_CEP,
  DATA_HORA D_TIMESTAMP NOT NULL,
  RESULTADO D_RESULTADO NOT NULL,
  LOGRADOURO D_DESCRICAO,
  BAIRRO D_NOME_CURTO,
  CIDADE D_NOME_CURTO,
  UF D_UF,
  COMPLEMENTO D_DESCRICAO,
  GATEWAY_USADO D_GATEWAY NOT NULL
);

CREATE TABLE GATEWAY_CONFIG (
  ID D_ID PRIMARY KEY,
  NOME D_GATEWAY NOT NULL UNIQUE,
  CLASSE D_DESCRICAO NOT NULL,
  URL_BASE D_DESCRICAO NOT NULL,
  ATIVO SMALLINT DEFAULT 0 CHECK (ATIVO IN (0, 1)),
  PRIORIDADE SMALLINT DEFAULT 1 CHECK (PRIORIDADE > 0)
);

CREATE INDEX IDX_CONSULTA_CEP ON CONSULTA_CEP (CEP);
CREATE INDEX IDX_CONSULTA_DATAHORA ON CONSULTA_CEP (DATA_HORA);
CREATE INDEX IDX_CONSULTA_RESULTADO ON CONSULTA_CEP (RESULTADO);

SET TERM ^;

CREATE TRIGGER TRG_CONSULTA_CEP_BI FOR CONSULTA_CEP
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = NEXT VALUE FOR SEQ_CONSULTA_CEP;
END^

CREATE TRIGGER TRG_GATEWAY_CONFIG_BI FOR GATEWAY_CONFIG
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = NEXT VALUE FOR SEQ_GATEWAY_CONFIG;
END^

CREATE PROCEDURE SP_SALVAR_CONSULTA (
  P_CEP D_CEP,
  P_RESULTADO D_RESULTADO,
  P_LOGRADOURO D_DESCRICAO,
  P_BAIRRO D_NOME_CURTO,
  P_CIDADE D_NOME_CURTO,
  P_UF D_UF,
  P_COMPLEMENTO D_DESCRICAO,
  P_GATEWAY_USADO D_GATEWAY
)
RETURNS (
  P_ID D_ID
)
AS
BEGIN
  P_ID = NEXT VALUE FOR SEQ_CONSULTA_CEP;

  INSERT INTO CONSULTA_CEP (
    ID, CEP, DATA_HORA, RESULTADO,
    LOGRADOURO, BAIRRO, CIDADE, UF,
    COMPLEMENTO, GATEWAY_USADO
  )
  VALUES (
    :P_ID, :P_CEP, CURRENT_TIMESTAMP, :P_RESULTADO,
    :P_LOGRADOURO, :P_BAIRRO, :P_CIDADE, :P_UF,
    :P_COMPLEMENTO, :P_GATEWAY_USADO
  );

  SUSPEND;
END^

CREATE PROCEDURE SP_LISTAR_HISTORICO
RETURNS (
  R_ID D_ID,
  R_CEP D_CEP,
  R_DATA_HORA D_TIMESTAMP,
  R_RESULTADO D_RESULTADO,
  R_LOGRADOURO D_DESCRICAO,
  R_BAIRRO D_NOME_CURTO,
  R_CIDADE D_NOME_CURTO,
  R_UF D_UF,
  R_COMPLEMENTO D_DESCRICAO,
  R_GATEWAY_USADO D_GATEWAY
)
AS
BEGIN
  FOR SELECT
    ID, CEP, DATA_HORA, RESULTADO,
    LOGRADOURO, BAIRRO, CIDADE, UF,
    COMPLEMENTO, GATEWAY_USADO
  FROM CONSULTA_CEP
  ORDER BY DATA_HORA DESC
  INTO
    :R_ID, :R_CEP, :R_DATA_HORA, :R_RESULTADO,
    :R_LOGRADOURO, :R_BAIRRO, :R_CIDADE, :R_UF,
    :R_COMPLEMENTO, :R_GATEWAY_USADO
  DO
    SUSPEND;
END^

CREATE PROCEDURE SP_OBTER_GATEWAY_ATIVO
RETURNS (
  R_NOME D_GATEWAY,
  R_CLASSE D_DESCRICAO,
  R_URL_BASE D_DESCRICAO
)
AS
BEGIN
  SELECT FIRST 1 NOME, CLASSE, URL_BASE
  FROM GATEWAY_CONFIG
  WHERE ATIVO = 1
  ORDER BY PRIORIDADE ASC
  INTO :R_NOME, :R_CLASSE, :R_URL_BASE;

  IF (R_NOME IS NOT NULL) THEN
    SUSPEND;
END^

SET TERM ;^

CREATE VIEW VW_HISTORICO_CONSULTAS AS
SELECT
  ID,
  CEP,
  DATA_HORA,
  RESULTADO,
  LOGRADOURO,
  BAIRRO,
  CIDADE,
  UF,
  COMPLEMENTO,
  GATEWAY_USADO
FROM CONSULTA_CEP;

INSERT INTO GATEWAY_CONFIG (NOME, CLASSE, URL_BASE, ATIVO, PRIORIDADE)
VALUES ('ViaCEP', 'TViaCEPAdapter', 'https://viacep.com.br/ws', 1, 1);

INSERT INTO GATEWAY_CONFIG (NOME, CLASSE, URL_BASE, ATIVO, PRIORIDADE)
VALUES ('BrasilAPI', 'TBrasilAPIAdapter', 'https://brasilapi.com.br/api/cep/v1', 0, 2);

COMMIT;

