/************************************************************
 * ConsultaCEP - DDL Firebird 3.0+
 * Character Set: UTF8 | Page Size: 16384
 *
 * Exemplo:
 * CREATE DATABASE 'C:\...\ConsultaCEP_MVC\Database\CONSULTACEP_MVC.FDB'
 *   PAGE_SIZE 16384
 *   DEFAULT CHARACTER SET UTF8;
 ************************************************************/

CREATE DOMAIN D_ID AS BIGINT NOT NULL;
CREATE DOMAIN D_CEP AS CHAR(8) CHARACTER SET UTF8
  CHECK (VALUE SIMILAR TO '[0-9]{8}');
CREATE DOMAIN D_RESULTADO AS VARCHAR(20) CHARACTER SET UTF8
  CHECK (VALUE IN ('SUCESSO', 'NAO_ENCONTRADO', 'ERRO_API'));
CREATE DOMAIN D_DESCRICAO AS VARCHAR(200) CHARACTER SET UTF8;
CREATE DOMAIN D_NOME_CURTO AS VARCHAR(100) CHARACTER SET UTF8;
CREATE DOMAIN D_UF AS CHAR(2) CHARACTER SET UTF8;
CREATE DOMAIN D_GATEWAY AS VARCHAR(50) CHARACTER SET UTF8;
CREATE DOMAIN D_TIMESTAMP AS TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE SEQUENCE SEQ_CONSULTA_CEP;

CREATE TABLE CONSULTA_CEP (
  ID D_ID PRIMARY KEY,
  CEP D_CEP,
  DATA_HORA D_TIMESTAMP NOT NULL,
  RESULTADO D_RESULTADO NOT NULL,
  LOGRADOURO D_DESCRICAO,
  BAIRRO D_NOME_CURTO,
  CIDADE D_NOME_CURTO,
  UF D_UF,
  COMPLEMENTO D_DESCRICAO,
  GATEWAY_USADO D_GATEWAY NOT NULL
);

CREATE INDEX IDX_CONSULTA_CEP ON CONSULTA_CEP (CEP);
CREATE INDEX IDX_CONSULTA_DATAHORA ON CONSULTA_CEP (DATA_HORA);
CREATE INDEX IDX_CONSULTA_RESULTADO ON CONSULTA_CEP (RESULTADO);

SET TERM ^;

CREATE PROCEDURE SP_SALVAR_CONSULTA (
  P_CEP D_CEP,
  P_RESULTADO D_RESULTADO,
  P_LOGRADOURO D_DESCRICAO,
  P_BAIRRO D_NOME_CURTO,
  P_CIDADE D_NOME_CURTO,
  P_UF D_UF,
  P_COMPLEMENTO D_DESCRICAO,
  P_GATEWAY_USADO D_GATEWAY
)
RETURNS (
  P_ID D_ID
)
AS
BEGIN
  P_ID = NEXT VALUE FOR SEQ_CONSULTA_CEP;

  INSERT INTO CONSULTA_CEP (
    ID, CEP, DATA_HORA, RESULTADO,
    LOGRADOURO, BAIRRO, CIDADE, UF,
    COMPLEMENTO, GATEWAY_USADO
  )
  VALUES (
    :P_ID, :P_CEP, CURRENT_TIMESTAMP, :P_RESULTADO,
    :P_LOGRADOURO, :P_BAIRRO, :P_CIDADE, :P_UF,
    :P_COMPLEMENTO, :P_GATEWAY_USADO
  );

  SUSPEND;
END^

SET TERM ;^

COMMIT;
